
# <center> Lab Exercise 2: Fundamental Python Libraries for Data Scientists </center>
<center>
Humberto Díaz <br>
The University of Winnipeg <br>
DIT 54102 AIW01: Foundations of Data Science <br>
Muhammad Shahin PhD. <br>
March 23, 2025 <br>
</center>

## Basic data types
Python supports several basic data types, including integers, floats, booleans, and strings. These types behave similarly to those in other languages.

### Numbers
Integers and floats in Python behave as expected. Note that Python does not support unary increment (x++) or decrement (x--) operators.

In [4]:
x = 3
print(type(x))  # Check the type of x
print(x)        # Print the value of x
print(x + 1)    # Perform addition
print(x - 1)    # Perform subtraction
print(x * 2)    # Perform multiplication
print(x ** 2)   # Perform exponentiation
x += 1          # Increment x by 1
print(x)        # Print the updated value of x
x *= 2          # Multiply x by 2
print(x)        # Print the updated value of x

y = 2.5
print(type(y))  # Check the type of y
print(y, y + 1, y * 2, y ** 2)  # Perform multiple operations on y

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


### Booleans
Python implements Boolean logic using English words instead of symbols (&&, ||, etc.):

In [6]:
t = True
f = False
print(type(t))  # Check the type of t
print(t and f)  # Logical AND operation
print(t or f)   # Logical OR operation
print(not t)    # Logical NOT operation
print(t != f)   # Logical XOR operation

<class 'bool'>
False
True
False
True


### Strings
Python provides excellent support for strings:


In [8]:
hello = 'hello'  # String with single quotes
world = "world"  # String with double quotes
print(hello)     # Print the string
print(len(hello))  # Print the length of the string
hw = hello + ' ' + world  # Concatenate strings
print(hw)  # Print the concatenated string

hello
5
hello world


String objects have many useful methods:

In [10]:
s = "hello"
print(s.capitalize())  # Capitalize the string
print(s.upper())       # Convert to uppercase
print(s.rjust(7))      # Right-justify the string
print(s.center(7))     # Center the string
print(s.replace('l', '(ell)'))  # Replace substrings
print('  world  '.strip())  # Remove leading and trailing whitespace

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


### Lists
A list in Python is similar to an array but is resizable and can contain elements of different types:

In [12]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Print the list and the element at index 2
print(xs[-1])     # Print the last element using negative indexing
xs[2] = 'foo'     # Modify the list to include mixed types
print(xs)         # Print the updated list
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Print the updated list
x = xs.pop()      # Remove and return the last element
print(x, xs)      # Print the popped element and the updated list

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


Slicing allows you to access sublists:



In [14]:
nums = list(range(5))  # Create a list of integers
print(nums)            # Print the list
print(nums[2:4])       # Slice from index 2 to 4 (exclusive)
print(nums[2:])        # Slice from index 2 to the end
print(nums[:2])        # Slice from the start to index 2 (exclusive)
print(nums[:])         # Slice the entire list
print(nums[:-1])       # Slice the list excluding the last element
nums[2:4] = [8, 9]     # Replace a sublist
print(nums)            # Print the updated list

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


#### Looping Over Lists
You can loop over list elements:

In [16]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)  # Print each animal

cat
dog
monkey


To access the index of each element, use enumerate:

In [18]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))  # Print index and animal

#1: cat
#2: dog
#3: monkey


### List Comprehensions
List comprehensions provide a concise way to transform data:

In [20]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]  # Create a list of squares
print(squares)  # Print the list of squares

[0, 1, 4, 9, 16]


In [21]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]  # Squares of even numbers
print(even_squares)  # Print the list of even squares

[0, 4, 16]


### Dictionaries
A dictionary stores (key, value) pairs:

In [23]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a dictionary
print(d['cat'])  # Access a value using a key
print('cat' in d)  # Check if a key exists
d['fish'] = 'wet'  # Add a new key-value pair
print(d['fish'])  # Access the new value
print(d.get('monkey', 'N/A'))  # Get a value with a default
print(d.get('fish', 'N/A'))  # Get a value with a default
del d['fish']  # Remove a key-value pair
print(d.get('fish', 'N/A'))  # Attempt to access the removed key

cute
True
wet
N/A
wet
N/A


Iterating over dictionary keys:

In [25]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))  # Print animal and leg count

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


To access both keys and values, use items():

In [27]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))  # Print key-value pairs

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Dictionary comprehensions:

In [29]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}  # Create a dictionary of even squares
print(even_num_to_square)  # Print the dictionary

{0: 0, 2: 4, 4: 16}


### Sets
A set is an unordered collection of distinct elements:

In [31]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in the set
print('fish' in animals)  # Check if an element is not in the set
animals.add('fish')       # Add an element to the set
print('fish' in animals)  # Check if the element was added
print(len(animals))       # Print the number of elements in the set
animals.add('cat')        # Add an existing element (no effect)
print(len(animals))       # Print the number of elements (unchanged)
animals.remove('cat')     # Remove an element from the set
print(len(animals))       # Print the updated number of elements

True
False
True
3
3
2


Iterating over a set:



In [33]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))  # Print index and animal

#1: cat
#2: dog
#3: fish


Set comprehensions:

In [35]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}  # Create a set of square roots
print(nums)  # Print the set

{0, 1, 2, 3, 4, 5}


### Tuples
A tuple is an immutable ordered list of values:

In [37]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)  # Create a tuple
print(type(t))  # Check the type of t
print(d[t])  # Access a value using a tuple key
print(d[(1, 2)])  # Access another value using a tuple key

<class 'tuple'>
5
1


## Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these arrays.

### Arrays
A numpy array is a grid of values, all of the same type, indexed by a tuple of nonnegative integers:

In [40]:
import numpy as np  # Import Numpy library as np

a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a))  # Check the type of the array
print(a.shape)  # Print the shape of the array
print(a[0], a[1], a[2])  # Print individual elements
a[0] = 5  # Modify an element
print(a)  # Print the updated array

b = np.array([[1, 2, 3], [4, 5, 6]])  # Create a rank 2 array
print(b.shape)  # Print the shape of the array
print(b[0, 0], b[0, 1], b[1, 0])  # Print individual elements

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


### Array Creation
Numpy provides functions to create arrays:

In [42]:
a = np.zeros((2, 2))  # Create an array of zeros
print(a)

b = np.ones((1, 2))  # Create an array of ones
print(b)

c = np.full((2, 2), 7)  # Create a constant array
print(c)

d = np.eye(2)  # Create a 2x2 identity matrix
print(d)

e = np.random.random((2, 2))  # Create an array with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.15640089 0.7422896 ]
 [0.26251048 0.0145216 ]]


### Array Indexing
Numpy arrays can be sliced:

In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[:2, 1:3]  # Slice the first 2 rows and columns 1 and 2
print(b)

b[0, 0] = 77  # Modify the slice
print(a[0, 1])  # The original array is also modified

[[2 3]
 [6 7]]
77


### Array Math
Basic mathematical functions operate elementwise:

In [46]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x + y)  # Elementwise sum
print(np.add(x, y))

print(x - y)  # Elementwise difference
print(np.subtract(x, y))

print(x * y)  # Elementwise product
print(np.multiply(x, y))

print(x / y)  # Elementwise division
print(np.divide(x, y))

print(np.sqrt(x))  # Elementwise square root

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Matrix multiplication is done using the dot function:

In [48]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))  # Inner product of vectors
print(np.dot(v, w))

print(x.dot(v))  # Matrix / vector product
print(np.dot(x, v))

print(x.dot(y))  # Matrix / matrix product
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Array Manipulation
Transposing a matrix:

In [50]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)  # Transpose the matrix

v = np.array([1, 2, 3])
print(v)
print(v.T)  # Transposing a rank 1 array does nothing

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### Broadcasting
Broadcasting allows numpy to work with arrays of different shapes:

In [52]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## Scipy
Scipy builds on Numpy and provides additional functions for scientific computing.

### Distance Between Points
Scipy provides functions to compute distances between points:

In [58]:
import numpy
import scipy
print(numpy.__version__)
print(scipy.__version__)


2.2.3
1.11.1
