
# <center> Lab Exercise 2: Fundamental Python Libraries for Data Scientists </center>
<center>
Humberto Díaz <br>
The University of Winnipeg <br>
DIT 54102 AIW01: Foundations of Data Science <br>
Muhammad Shahin PhD. <br>
March 23, 2025 <br>
</center>

## Creating NumPy Arrays (with the example in class)
<img src="6x6array.png" width="200">

In [5]:
# creating 2D example array 6x6
import numpy as np
a = np.array([[0, 1, 2, 3, 4, 5],
              [10, 11, 12, 13, 14, 15],
             [20, 21, 22, 23, 24, 25], 
             [30, 31, 32, 33, 34, 35], 
             [40, 41, 42, 43, 44, 45], 
             [50, 51, 52, 53, 54, 55]])

In [7]:
a[0, 3:5]

array([3, 4])

In [11]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [13]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [15]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])